# outputs.conf - Kali Linux Universal Forwarder
# Place at: /opt/splunkforwarder/etc/system/local/outputs.conf
#
# Sending to Windows VM (Splunk indexer) on port 9997
# Make sure port 9997 is open on Windows firewall

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = 192.168.56.128:9997

[tcpout-server://192.168.56.128:9997]
